import { Product } from './Product';

export const MOCK_PRODUCT = [
  new Product({
    id: 1,
    name: 'Tranh mèo canvas',
    tag_name: 'tranh-meo-canvas',
    description: '',
    category_id: 1,
    images: '',
    status: 'is_active',
    seo_title: '',
    seo_description: '',
    user_id: 1,
    created_at: '2012-08-06T21:21:31.419Z',
  }),
  new Product({
    id: 2,
    name: 'Tranh mèo canvas',
    tag_name: 'tranh-meo-canvas',
    description: '',
    category_id: 1,
    images: '',
    status: 'is_active',
    seo_title: '',
    seo_description: '',
    user_id: 1,
    created_at: '2012-08-06T21:21:31.419Z',
  }),
  new Product({
    id: 3,
    name: 'Tranh mèo canvas',
    tag_name: 'tranh-meo-canvas',
    description: '',
    category_id: 1,
    images: '',
    status: 'is_active',
    seo_title: '',
    seo_description: '',
    user_id: 2,
    created_at: '2012-08-06T21:21:31.419Z',
  }),
  new Product({
    id: 4,
    name: 'Tranh mèo canvas',
    tag_name: 'tranh-meo-canvas',
    description: '',
    category_id: 1,
    images: '',
    status: 'is_active',
    seo_title: '',
    seo_description: '',
    user_id: 1,
    created_at: '2012-08-06T21:21:31.419Z',
  }),
];